name: 'Check Commits using Commitizen'
description: 'Verify that commits match configured commitizen rules'
branding:
  icon: 'git-commit'
  color: 'purple'
inputs:
  commitizen_version:
    description: 'Specify the version to be used by commitizen'
    required: false
    default: latest
  github_token:
    description: 'Token for the repo. Can be passed in using $\{{ secrets.GITHUB_TOKEN }}'
    required: false
  debug:
    description: "If true, prints debug output to GitHub Actions stdout."
    required: false
    default: "false"
runs:
  using: "composite"
  steps:
    - shell: bash
      run: |
        if [[ ${{ inputs.debug }} == "true" ]]; then
          set -x
        fi
        # TODO: This should just use the container image
        # https://github.com/commitizen-tools/commitizen-docker-image
        if [[ -n "${{ inputs.commitizen_version }}" ]]; then
          pip install -U commitizen==${{ inputs.commitizen_version }}
        else
          pip install -U commitizen
        fi

        cz check --rev-range ${{ github.event.pull_request.base.sha }}..${{ github.event.pull_request.head.sha }}
